"""empty message

Revision ID: 2849f5f705ed
Revises: 
Create Date: 2022-09-09 18:12:33.898428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2849f5f705ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parsingtask',
    sa.Column('guid', sa.String(length=34), nullable=False),
    sa.Column('source_link', sa.String(length=255), nullable=False),
    sa.Column('target_file', sa.String(length=255), nullable=False),
    sa.Column('parsing_status', sa.Enum('Project', 'In process', 'Complite', 'Declined', 'Cleared', name='parsingstatus'), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('guid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parsingtask')
    # ### end Alembic commands ###
