"""empty message

Revision ID: 508de76313cf
Revises: 7fe7abcf5021
Create Date: 2022-09-09 18:15:53.561422

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '508de76313cf'
down_revision = '7fe7abcf5021'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('parsingtask', 'parsing_status',
               existing_type=mysql.ENUM('Project', 'In process', 'Complite', 'Declined', 'Cleared'),
               nullable=False)
    op.alter_column('parsingtask', 'parsing_type',
               existing_type=mysql.ENUM('AA', 'NA', 'AA+NA'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('parsingtask', 'parsing_type',
               existing_type=mysql.ENUM('AA', 'NA', 'AA+NA'),
               nullable=True)
    op.alter_column('parsingtask', 'parsing_status',
               existing_type=mysql.ENUM('Project', 'In process', 'Complite', 'Declined', 'Cleared'),
               nullable=True)
    # ### end Alembic commands ###
