"""empty message

Revision ID: c040ab6b2da1
Revises: 508de76313cf
Create Date: 2022-09-09 19:06:18.653706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c040ab6b2da1'
down_revision = '508de76313cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parsingtask',
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('source_link', sa.String(length=255), nullable=False),
    sa.Column('target_file', sa.String(length=255), nullable=False),
    sa.Column('parsing_status', sa.Enum('Project', 'In process', 'Complite', 'Declined', 'Cleared', name='parsingstatus'), nullable=False),
    sa.Column('parsing_type', sa.Enum('AA', 'NA', 'AA+NA', name='parsingtype'), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('guid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parsingtask')
    # ### end Alembic commands ###
